### ISSUE TITLE
Use Vector4 instead of Vector3 for Triangle3f

### ISSUE THREAD

**Issue by dialupnoises** [TheBerkin/StdPaint#3]
This is an easy issue to fix (which I did in cpancake/StdPaint@09c312d1cc290a819f520a7206036b0cd7ea07de), but I thought I should make this issue to make you aware of it. Vector4 should be used internally by Triangle3f, because Vector4 is what is needed to render (though in theory, you could make an operator overload for Matrix4 \* Vector3 that returns a Vector4), so it's faster and easier to use it internally than to convert it every time.

Just a simple change, and you could implement the operator overload if you wanted to instead.

**Comment by dialupnoises** [comment]
It might also be better to merge my fork (I can make a pull request if you want) and solve some of the type differences we have here.

**Comment by TheBerkin** [comment]
I think the operator overload route is better, as updating the triangle to use 4D vectors would require me to make a bunch of other operator overloads for Vector4. Less work overall.

Definitely make a pull request.

Edit: Just saw that your version includes all the necessary overloads to change the class. Oops.

**Comment by dialupnoises** [comment]
Reverted it back + fixed Camera to project Vector3's anyways. Made a pull request (#4)
